version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

#hooks:
#  # 배포 후 custom 작업 정의
#  AfterInstall:
#    - location: ./app/scripts/deploy-prod.sh
#      timeout: 180
#      runas: root   # docker